version: 2.1

workflows: 
  odpalTest:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/openjdk:23.0.1
    steps:
      - checkout
      - run: 
          name: maven-install
          command: apt-get update && apt-get install -y maven
      - run:
          name: odpal-testy
          command: mvn test
